Admission/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
# import notifications.urls


admin.site.site_header = 'Student Admission'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include( 'Student.urls')),
    path('',include( 'Teachers.urls')),
    path('',include( 'student_dashboard.urls')),
    path('accounts/',include ('accounts.urls')),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Student/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Student import Lectureviews, views

app_name = "Student"

urlpatterns = [
    # path('Student_Admission', views.Student_Admission , name='Student_Admission'  ),
    # path('Home', views.Student_Admission , name="Home" ),
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    path('Payment', views.Payment , name='Payment' ),
    path('Revenue',views.revenue,name='Revenue'),
    path('totalrevenue',views.totalrevenue,name='totalrevenue'),
    path('invoice', views.invoice , name='invoice' ),
    path('admintm', views.admintm , name='Admin-Dashboard'  ),
    path('Admin-Dashboard', views.admintm , name='Admin-Dashboard'  ),
    path('data-tables', views.data_tables, name= 'data-tables'),
    path('edit-course/<int:id>/', views.Edit_course , name='edit-course' ),
#
    path('edit-course2/<int:id>/', views.Edit_course2 , name='edit-course2' ),#form pass
    path('delete_course/<int:id>/', views.Delete_course , name='delete_course' ),
    path('courses_table', views.courses_table, name= 'courses_table'),
    # path('course_edit_test/<ID>', views.course_edit_test , name='course_edit_test' ) ,
    path('user_details', views.user_details, name= 'user_details'),
    
    # admin student page 
    path('admin-student' , views.Student , name="admin-student"),
    path('admin-manage_student' , views.manage_student , name="admin-manage_student"),
    path('admin_student_edit/<int:id>/' , views.admin_student_edit , name="admin_student_edit"),
    path('manage_student_del/<int:id>/' , views.student_del , name="manage_student_del"),
    path('admin_new_student' , views.admin_new_student , name="admin_new_student"),
    path('admin_paid_student' , views.admin_paid_student , name="admin_paid_student"),
    path('add-student' , views.Add_student , name="add-student"),
    path('HOME' , views.HOME , name="HOME"),
    path('' , views.HOME , name="HOME"),
    # Lecture
    path('Lecture',Lectureviews.Lectures ,name='Lecture'),
    path('Lecture-home',Lectureviews.Lecture_home ,name='Lecture-home'),
    path('Manage-Lecture',Lectureviews.Lecture_manage ,name='Manage-Lecture'),
    path('Lecture_edit/<int:id>/',Lectureviews.Lecture_edit ,name='Lecture_edit')


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/Lecture/lecture.html
<style>
    .navbar{
        display: none!important;
    }
    /* body{ */
        /* background-image: linear-gradient(to bottom, rgb(139, 226, 238) , rgb(47, 89, 97) ,rgb(0, 0, 0)); */
        /* background-color: paleturquoise!important ; */
    /* } */
    .container{
        justify-content: center;
        text-align: center;
        margin-top: 20px;
        /* border: 1px solid black; */
    }
    form{
        padding: 10px;
        
        /* background-color: #4d868f; */
        /* background-color: red; */
        border-radius: 10px;
    }
    
</style>
{% extends 'nav.html' %}
{% block body %}
   <div class="container">
    <h1 class="btn-warning my-2">Add Lecture </h1>

       <form  method="POST" class="row" enctype="multipart/form-data"  action="" >
           {% csrf_token %}
           <input type="hidden" name="form_name" value="Edit" >
           {{form.media|safe  }}
           {{form.as_p|safe }}
           
          
           <!-- <button type="submit" class="w-100 btn btn-success">add</button> -->
           
           
           <div class="modal-footer">
               <a href="/Lecture-home" class="btn btn-danger">Cancel</a>
               <button type="submit" class="btn btn-primary">Add</button>
           </div>
        </div>
    </form>
    
    
</div> 
{% endblock %}   
   

templates/Lecture/lectureIndex.html
{% extends 'admintm\admin-nav.html' %}
{% block body %}
<!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
            <div class="card">
              <div class="card-header p-3 pt-2">
                <div class="icon icon-lg icon-shape bg-gradient-danger shadow-dark text-center border-radius-xl mt-n4 position-absolute">
                  <i class="material-icons opacity-10">weekend</i>
                </div>
                <div class="text-end pt-1">
                  <p class="text-sm mb-0 text-capitalize">Add Lecture</p>
                  <h4 class="mb-0">New</h4>
                </div>
              </div>
              <hr class="dark horizontal my-0">
              <div class="card-footer p-3">
                <a href="/Lecture"><p class="mb-0 text-center bg-gradient-danger border-radius-xl text-white"><i class="fas fa-user mr-5" style="padding-right: 15px;"></i><span class="text-success text-sm font-weight-bolder"></span>Add Lecture</p></a>
              </div>
            </div>
          </div>
         
          <!-- ./col -->
          <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
            <div class="card">
              <div class="card-header p-3 pt-2">
                <div class="icon icon-lg icon-shape bg-gradient-primary shadow-success text-center border-radius-xl mt-n4 position-absolute">
                  <i class="material-icons opacity-10">weekend</i>
                </div>
                <div class="text-end pt-1">
                  <p class="text-sm mb-0 text-capitalize">Manage Lecture</p>
                  <h4 class="mb-0">{{LectureCount}}</h4>
                </div>
              </div>
              <hr class="dark horizontal my-0">
              <div class="card-footer p-3">
                <a href="/Manage-Lecture"><p class="mb-0 text-center bg-gradient-primary border-radius-xl text-white"><i class="fas fa-user mr-5" style="padding-right: 15px;"></i><span class="text-success text-sm font-weight-bolder"></span>Manage Lecture</p></a>
              </div>
            </div>
          </div>
          <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
            <div class="card">
              <div class="card-header p-3 pt-2">
                <div class="icon icon-lg icon-shape bg-gradient-success shadow-dark text-center border-radius-xl mt-n4 position-absolute">
                  <i class="material-icons opacity-10">weekend</i>
                </div>
                <div class="text-end pt-1">
                  <p class="text-sm mb-0 text-capitalize">Lecture any</p>
                  <h4 class="mb-0">Any</h4>
                </div>
              </div>
              <hr class="dark horizontal my-0">
              <div class="card-footer p-3">
                <a href="#"><p class="mb-0 text-center bg-gradient-success border-radius-xl text-white"><i class="fas fa-user mr-5" style="padding-right: 15px;"></i><span class="text-success text-sm font-weight-bolder"></span>Manage Any</p></a>
              </div>
            </div>
          </div>
          
          
          
        </div>
        
    </section>

{% endblock %}

templates/Lecture/lecture_edit.html
<div id="contact" class="tab-pane" role="tabpanel" aria-labelledby="contact-tab">
                <form enctype="multipart/form-data" method="post">
                  <input type="hidden" name="form_name" value="ADD">
                  {% csrf_token %}
                  {{ form.media|safe}}
                  {{ form.as_table|safe}}
                  <button type="submit" class="btn btn-danger">submit</button>
                </form>
              </div>

templates/Lecture/lecture_manage.html
<style>
  .card-header {
    display: flex;

  }

  .modal-body {
    background-color: #ffff;

  }


  .add_headline {

    justify-self: start !important;
    width: 100%;
  }

  .add_btn {
    float: end !important;
    /* justify-self: end;  */
  }

  .td_btn {
    display: flex;
  }

  .errorlist {
    display: none;
  }
</style>
{% extends 'admintm\admin-nav.html' %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->

{% block body %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- <form method="POST" enctype="multipart/form-data">{% csrf_token %}
          <input type="hidden" name="form" value="ADD">
          {{ form.media|safe}}
          {{ form.as_p|safe}}
        </form> -->
        <div class="card">
          <div class="card-header text-primary" style="border-bottom: 1px solid gainsboro;">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button"
                  role="tab" aria-controls="home" aria-selected="true">List</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button"
                  role="tab" aria-controls="profile" aria-selected="false">Manage</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button"
                  role="tab" aria-controls="contact" aria-selected="false">Add</button>
              </li>
            </ul>
          </div>
          <!-- tab pane -->
          <dvv class="card-body">
            <div class="tab-content p-1">
              <div id="home" class="tab-pane fade show active" role="tabpanel" aria-labelledby="home-tab">
                <table id="example2" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Lecture Number</th>
                      <th>Lecture week</th>
                      <th>Lecture title</th>
                      <th>Lecture Details</th>
                      <th>Course </th>
                      {% comment %} <th>Edit</th> {% endcomment %}
                      {% comment %} <th>Delete</th> {% endcomment %}

                      {% comment %} <th>Number</th> {% endcomment %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in Lecture %}
                    <tr>
                      <td>{{item.lecture_num}}</td>
                      <td>{{item.week_num}}</td>
                      <td>{{item.title}}</td>
                      <td>{{item.description|safe}}</td>
                      <td>{{item.course}}</td>
                      {% comment %} <td><a href="{% url 'Student:edit-course2' item.id  %}"><i class="fas fa-edit"></i></a></td> {% endcomment %}
                      {% comment %} <td><a href="{% url 'Student:delete_course' item.id %}"><i class="fas fa-trash-alt"></i></a></td> {% endcomment %}


                      {% comment %} <td>Null</td> {% endcomment %}
                    </tr>
                    {% endfor %}



                  </tbody>
                </table>
              </div>

              <div id="profile" class="tab-pane fade" role="tabpanel" aria-labelledby="profile-tab">
                <table id="example2" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Lecture Number</th>
                      <th>Lecture week</th>
                      <th>Lecture title</th>
                      <th>Lecture Details</th>
                      <th>Course </th>
                      <th>Edit</th>
                      <th>Delete</th>

                      {% comment %} <th>Number</th> {% endcomment %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in Lecture %}
                    <tr>
                      <td>{{item.lecture_num}}</td>
                      <td>{{item.week_num}}</td>
                      <td>{{item.title}}</td>
                      <td>{{item.description|safe}}</td>
                      <td>{{item.course}}</td>
                      <td><a href="{% url 'Student:Lecture_edit' item.id  %}"><i class="fas fa-edit"></i></a></td>
                      <td><a href="{% url 'Student:Lecture_edit' item.id %}"><i class="fas fa-trash-alt"></i></a></td>


                      {% comment %} <td>Null</td> {% endcomment %}
                    </tr>
                    {% endfor %}



                  </tbody>
                </table>

              </div>


              <div id="contact" class="tab-pane" role="tabpanel" aria-labelledby="contact-tab">
                <form enctype="multipart/form-data" method="post">
                  <input type="hidden" name="form_name" value="ADD">
                  {% csrf_token %}
                  {{ form.media|safe}}
                  {{ form.as_table|safe}}
                  <button type="submit" class="btn btn-danger">submit</button>
                </form>
              </div>


            </div>




            <!-- /.card-header -->
            <!-- <div class="card-body"> -->

            <!-- </div> -->
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->



</section>


{% endblock %}